SELECT ITEMNO, DESCRIPTION, WEIGHT
FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

SELECT DISTINCT WAREHOUSES.WID, WNAME, LOCATION
FROM WAREHOUSES
INNER JOIN CITIES ON WAREHOUSES.CITY = CITIES.CITY
WHERE CITIES.CITY = 'Pune';

SELECT CUSTOMER.CNO, CNAME, ITEMS.ITEMNO, DESCRIPTION, ORDERED_QUANTITY
FROM CUSTOMER
INNER JOIN ORDERS ON CUSTOMER.CNO = ORDERS.CNO
INNER JOIN ORDER_ITEMS ON ORDERS.ONO = ORDER_ITEMS.ONO
INNER JOIN ITEMS ON ORDER_ITEMS.ITEMNO = ITEMS.ITEMNO
WHERE CNAME = 'Mr. Patil';

SELECT WAREHOUSES.WID, WNAME, LOCATION, COUNT(STORES.SID) AS STORE_COUNT
FROM WAREHOUSES
LEFT JOIN STORES ON WAREHOUSES.WID = STORES.WID
GROUP BY WAREHOUSES.WID, WNAME, LOCATION
ORDER BY STORE_COUNT DESC
LIMIT 1;

SELECT ITEMS.ITEMNO, DESCRIPTION, MIN(ORDERED_QUANTITY) AS MIN_ORDERED_QUANTITY
FROM ITEMS
LEFT JOIN ORDER_ITEMS ON ITEMS.ITEMNO = ORDER_ITEMS.ITEMNO
GROUP BY ITEMS.ITEMNO, DESCRIPTION
ORDER BY MIN_ORDERED_QUANTITY
LIMIT 1;

SELECT CUSTOMER.CNO, CNAME, ORDERS.ONO, ODATE, ITEMS.ITEMNO, DESCRIPTION, ORDERED_QUANTITY
FROM CUSTOMER
INNER JOIN ORDERS ON CUSTOMER.CNO = ORDERS.CNO
INNER JOIN ORDER_ITEMS ON ORDERS.ONO = ORDER_ITEMS.ONO
INNER JOIN ITEMS ON ORDER_ITEMS.ITEMNO = ITEMS.ITEMNO;
