-- Create the CITIES table
CREATE TABLE CITIES (
    CITY CHAR(20) PRIMARY KEY,
    STATE CHAR(20)
);

-- Create the WAREHOUSES table with a foreign key reference to CITIES
CREATE TABLE WAREHOUSES (
    WID INTEGER PRIMARY KEY,
    WNAME CHAR(30),
    LOCATION CHAR(20),
    CITY CHAR(20),
    FOREIGN KEY (CITY) REFERENCES CITIES(CITY)
);

-- Create the STORES table with a foreign key reference to CITIES and WAREHOUSES
CREATE TABLE STORES (
    SID INTEGER PRIMARY KEY,
    STORE_NAME CHAR(20),
    LOCATION_CITY CHAR(20),
    WID INTEGER,
    FOREIGN KEY (LOCATION_CITY) REFERENCES CITIES(CITY),
    FOREIGN KEY (WID) REFERENCES WAREHOUSES(WID)
);

-- Create the CUSTOMER table with a foreign key reference to CITIES
CREATE TABLE CUSTOMER (
    CNO INTEGER PRIMARY KEY,
    CNAME CHAR(50),
    ADDR VARCHAR(50),
    CU_CITY CHAR(20),
    FOREIGN KEY (CU_CITY) REFERENCES CITIES(CITY)
);

-- Create the ORDERS table with a foreign key reference to CUSTOMER
CREATE TABLE ORDERS (
    ONO INT PRIMARY KEY,
    ODATE DATE,
    CNO INTEGER,
    FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO)
);

-- Create the ITEMS table
CREATE TABLE ITEMS (
    ITEMNO INTEGER PRIMARY KEY,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2)
);

-- Create the ORDER_ITEMS table for the many-to-many relationship between ORDERS and ITEMS
CREATE TABLE ORDER_ITEMS (
    ONO INT,
    ITEMNO INTEGER,
    ORDERED_QUANTITY INTEGER,
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);

-- Create the STORE_ITEMS table for the many-to-many relationship between STORES and ITEMS
CREATE TABLE STORE_ITEMS (
    SID INTEGER,
    ITEMNO INTEGER,
    QUANTITY INTEGER,
    FOREIGN KEY (SID) REFERENCES STORES(SID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);
